title: TypeScript Hero
description: VSCode extension that aids you with your everyday work around typescript
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
